application: nmsverse
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Flask Restful handler
- url: /.*
  script: app.app.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
